# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/csmajs/anels048/final-project-mhsie026-jim023-anels048-vselv001

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/home/csmajs/anels048/final-project-mhsie026-jim023-anels048-vselv001

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/home/csmajs/anels048/final-project-mhsie026-jim023-anels048-vselv001/CMakeFiles /data/home/csmajs/anels048/final-project-mhsie026-jim023-anels048-vselv001//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/home/csmajs/anels048/final-project-mhsie026-jim023-anels048-vselv001/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/build
.PHONY : game/fast

#=============================================================================
# Target rules for targets named ChessGameExecutable

# Build rule for target.
ChessGameExecutable: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ChessGameExecutable
.PHONY : ChessGameExecutable

# fast build rule for target.
ChessGameExecutable/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChessGameExecutable.dir/build.make CMakeFiles/ChessGameExecutable.dir/build
.PHONY : ChessGameExecutable/fast

lib/Board.o: lib/Board.cpp.o
.PHONY : lib/Board.o

# target to build an object file
lib/Board.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/Board.cpp.o
.PHONY : lib/Board.cpp.o

lib/Board.i: lib/Board.cpp.i
.PHONY : lib/Board.i

# target to preprocess a source file
lib/Board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/Board.cpp.i
.PHONY : lib/Board.cpp.i

lib/Board.s: lib/Board.cpp.s
.PHONY : lib/Board.s

# target to generate assembly for a file
lib/Board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/Board.cpp.s
.PHONY : lib/Board.cpp.s

lib/Display.o: lib/Display.cpp.o
.PHONY : lib/Display.o

# target to build an object file
lib/Display.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/Display.cpp.o
.PHONY : lib/Display.cpp.o

lib/Display.i: lib/Display.cpp.i
.PHONY : lib/Display.i

# target to preprocess a source file
lib/Display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/Display.cpp.i
.PHONY : lib/Display.cpp.i

lib/Display.s: lib/Display.cpp.s
.PHONY : lib/Display.s

# target to generate assembly for a file
lib/Display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/Display.cpp.s
.PHONY : lib/Display.cpp.s

lib/Game.o: lib/Game.cpp.o
.PHONY : lib/Game.o

# target to build an object file
lib/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/Game.cpp.o
.PHONY : lib/Game.cpp.o

lib/Game.i: lib/Game.cpp.i
.PHONY : lib/Game.i

# target to preprocess a source file
lib/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/Game.cpp.i
.PHONY : lib/Game.cpp.i

lib/Game.s: lib/Game.cpp.s
.PHONY : lib/Game.s

# target to generate assembly for a file
lib/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/Game.cpp.s
.PHONY : lib/Game.cpp.s

lib/bishop.o: lib/bishop.cpp.o
.PHONY : lib/bishop.o

# target to build an object file
lib/bishop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/bishop.cpp.o
.PHONY : lib/bishop.cpp.o

lib/bishop.i: lib/bishop.cpp.i
.PHONY : lib/bishop.i

# target to preprocess a source file
lib/bishop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/bishop.cpp.i
.PHONY : lib/bishop.cpp.i

lib/bishop.s: lib/bishop.cpp.s
.PHONY : lib/bishop.s

# target to generate assembly for a file
lib/bishop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/bishop.cpp.s
.PHONY : lib/bishop.cpp.s

lib/king.o: lib/king.cpp.o
.PHONY : lib/king.o

# target to build an object file
lib/king.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/king.cpp.o
.PHONY : lib/king.cpp.o

lib/king.i: lib/king.cpp.i
.PHONY : lib/king.i

# target to preprocess a source file
lib/king.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/king.cpp.i
.PHONY : lib/king.cpp.i

lib/king.s: lib/king.cpp.s
.PHONY : lib/king.s

# target to generate assembly for a file
lib/king.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/king.cpp.s
.PHONY : lib/king.cpp.s

lib/knight.o: lib/knight.cpp.o
.PHONY : lib/knight.o

# target to build an object file
lib/knight.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/knight.cpp.o
.PHONY : lib/knight.cpp.o

lib/knight.i: lib/knight.cpp.i
.PHONY : lib/knight.i

# target to preprocess a source file
lib/knight.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/knight.cpp.i
.PHONY : lib/knight.cpp.i

lib/knight.s: lib/knight.cpp.s
.PHONY : lib/knight.s

# target to generate assembly for a file
lib/knight.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/knight.cpp.s
.PHONY : lib/knight.cpp.s

lib/pawn.o: lib/pawn.cpp.o
.PHONY : lib/pawn.o

# target to build an object file
lib/pawn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/pawn.cpp.o
.PHONY : lib/pawn.cpp.o

lib/pawn.i: lib/pawn.cpp.i
.PHONY : lib/pawn.i

# target to preprocess a source file
lib/pawn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/pawn.cpp.i
.PHONY : lib/pawn.cpp.i

lib/pawn.s: lib/pawn.cpp.s
.PHONY : lib/pawn.s

# target to generate assembly for a file
lib/pawn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/pawn.cpp.s
.PHONY : lib/pawn.cpp.s

lib/queen.o: lib/queen.cpp.o
.PHONY : lib/queen.o

# target to build an object file
lib/queen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/queen.cpp.o
.PHONY : lib/queen.cpp.o

lib/queen.i: lib/queen.cpp.i
.PHONY : lib/queen.i

# target to preprocess a source file
lib/queen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/queen.cpp.i
.PHONY : lib/queen.cpp.i

lib/queen.s: lib/queen.cpp.s
.PHONY : lib/queen.s

# target to generate assembly for a file
lib/queen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/queen.cpp.s
.PHONY : lib/queen.cpp.s

lib/rook.o: lib/rook.cpp.o
.PHONY : lib/rook.o

# target to build an object file
lib/rook.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/rook.cpp.o
.PHONY : lib/rook.cpp.o

lib/rook.i: lib/rook.cpp.i
.PHONY : lib/rook.i

# target to preprocess a source file
lib/rook.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/rook.cpp.i
.PHONY : lib/rook.cpp.i

lib/rook.s: lib/rook.cpp.s
.PHONY : lib/rook.s

# target to generate assembly for a file
lib/rook.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/rook.cpp.s
.PHONY : lib/rook.cpp.s

lib/ui.o: lib/ui.cpp.o
.PHONY : lib/ui.o

# target to build an object file
lib/ui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/ui.cpp.o
.PHONY : lib/ui.cpp.o

lib/ui.i: lib/ui.cpp.i
.PHONY : lib/ui.i

# target to preprocess a source file
lib/ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/ui.cpp.i
.PHONY : lib/ui.cpp.i

lib/ui.s: lib/ui.cpp.s
.PHONY : lib/ui.s

# target to generate assembly for a file
lib/ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/lib/ui.cpp.s
.PHONY : lib/ui.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChessGameExecutable.dir/build.make CMakeFiles/ChessGameExecutable.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChessGameExecutable.dir/build.make CMakeFiles/ChessGameExecutable.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChessGameExecutable.dir/build.make CMakeFiles/ChessGameExecutable.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ChessGameExecutable"
	@echo "... game"
	@echo "... lib/Board.o"
	@echo "... lib/Board.i"
	@echo "... lib/Board.s"
	@echo "... lib/Display.o"
	@echo "... lib/Display.i"
	@echo "... lib/Display.s"
	@echo "... lib/Game.o"
	@echo "... lib/Game.i"
	@echo "... lib/Game.s"
	@echo "... lib/bishop.o"
	@echo "... lib/bishop.i"
	@echo "... lib/bishop.s"
	@echo "... lib/king.o"
	@echo "... lib/king.i"
	@echo "... lib/king.s"
	@echo "... lib/knight.o"
	@echo "... lib/knight.i"
	@echo "... lib/knight.s"
	@echo "... lib/pawn.o"
	@echo "... lib/pawn.i"
	@echo "... lib/pawn.s"
	@echo "... lib/queen.o"
	@echo "... lib/queen.i"
	@echo "... lib/queen.s"
	@echo "... lib/rook.o"
	@echo "... lib/rook.i"
	@echo "... lib/rook.s"
	@echo "... lib/ui.o"
	@echo "... lib/ui.i"
	@echo "... lib/ui.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

